# Required
version: 2

# Image to use
build:
  image: testing

# Configuration
python:
  version: 3.9
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
     
formats: []

sphinx:
  builder: html
  configuration: docs/conf.py
